// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQh7h880MEWRxVuQ78K9IhY75fumIhVoA',
    appId: '1:110359614666:web:784fce74b8b43c13d35033',
    messagingSenderId: '110359614666',
    projectId: 'smart-learning-room-iot',
    authDomain: 'smart-learning-room-iot.firebaseapp.com',
    databaseURL: 'https://smart-learning-room-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-learning-room-iot.firebasestorage.app',
    measurementId: 'G-T0MKDWLNJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqSSTT59KNrlbikXJ1Se7qGEz1TNfznGs',
    appId: '1:110359614666:android:404e5620b9cd367ed35033',
    messagingSenderId: '110359614666',
    projectId: 'smart-learning-room-iot',
    databaseURL: 'https://smart-learning-room-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-learning-room-iot.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-H1lkB_l5jWzALPo2mScXCEYk9fcyiRc',
    appId: '1:110359614666:ios:b8f4ba774f499221d35033',
    messagingSenderId: '110359614666',
    projectId: 'smart-learning-room-iot',
    databaseURL: 'https://smart-learning-room-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-learning-room-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartLearningRoom',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-H1lkB_l5jWzALPo2mScXCEYk9fcyiRc',
    appId: '1:110359614666:ios:b8f4ba774f499221d35033',
    messagingSenderId: '110359614666',
    projectId: 'smart-learning-room-iot',
    databaseURL: 'https://smart-learning-room-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-learning-room-iot.firebasestorage.app',
    iosBundleId: 'com.example.smartLearningRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQh7h880MEWRxVuQ78K9IhY75fumIhVoA',
    appId: '1:110359614666:web:75438140a5fad5e6d35033',
    messagingSenderId: '110359614666',
    projectId: 'smart-learning-room-iot',
    authDomain: 'smart-learning-room-iot.firebaseapp.com',
    databaseURL: 'https://smart-learning-room-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-learning-room-iot.firebasestorage.app',
    measurementId: 'G-LK06GQZV5Z',
  );
}
